import type { WordPair } from './room.js';
import type { WordLocale } from './room.js';

export interface WordDeckEntry extends WordPair {
  category: string;
}

export const DEFAULT_WORD_DECK: WordDeckEntry[] = [
  { category: 'Food', a: 'Pizza', b: 'Empanada' },
  { category: 'Food', a: 'Burger', b: 'Hot Dog' },
  { category: 'Food', a: 'Sushi', b: 'Tacos' },
  { category: 'Food', a: 'Pasta', b: 'Risotto' },
  { category: 'Food', a: 'Pancakes', b: 'Waffles' },
  { category: 'Food', a: 'Soup', b: 'Stew' },
  { category: 'Food', a: 'Apple', b: 'Banana' },
  { category: 'Food', a: 'Coffee', b: 'Tea' },
  { category: 'Places', a: 'Beach', b: 'Desert' },
  { category: 'Places', a: 'Mountain', b: 'Valley' },
  { category: 'Places', a: 'City', b: 'Town' },
  { category: 'Places', a: 'Airport', b: 'Train Station' },
  { category: 'Places', a: 'Library', b: 'Museum' },
  { category: 'Places', a: 'Stadium', b: 'Theater' },
  { category: 'Places', a: 'Park', b: 'Plaza' },
  { category: 'Places', a: 'Hospital', b: 'Clinic' },
  { category: 'Sports', a: 'Soccer', b: 'Basketball' },
  { category: 'Sports', a: 'Baseball', b: 'Cricket' },
  { category: 'Sports', a: 'Tennis', b: 'Badminton' },
  { category: 'Sports', a: 'Golf', b: 'Bowling' },
  { category: 'Sports', a: 'Running', b: 'Cycling' },
  { category: 'Sports', a: 'Swimming', b: 'Surfing' },
  { category: 'Sports', a: 'Volleyball', b: 'Handball' },
  { category: 'Sports', a: 'Boxing', b: 'Wrestling' },
  { category: 'Animals', a: 'Tiger', b: 'Lion' },
  { category: 'Animals', a: 'Dog', b: 'Wolf' },
  { category: 'Animals', a: 'Cat', b: 'Fox' },
  { category: 'Animals', a: 'Eagle', b: 'Hawk' },
  { category: 'Animals', a: 'Shark', b: 'Dolphin' },
  { category: 'Animals', a: 'Horse', b: 'Donkey' },
  { category: 'Animals', a: 'Rabbit', b: 'Hare' },
  { category: 'Animals', a: 'Bear', b: 'Panda' },
  { category: 'Tech', a: 'Laptop', b: 'Tablet' },
  { category: 'Tech', a: 'Keyboard', b: 'Mouse' },
  { category: 'Tech', a: 'Phone', b: 'Camera' },
  { category: 'Tech', a: 'Browser', b: 'Search Engine' },
  { category: 'Tech', a: 'Wi-Fi', b: 'Bluetooth' },
  { category: 'Tech', a: 'Robot', b: 'Drone' },
  { category: 'Tech', a: 'Printer', b: 'Scanner' },
  { category: 'Tech', a: 'Headphones', b: 'Speakers' },
  { category: 'Jobs', a: 'Teacher', b: 'Professor' },
  { category: 'Jobs', a: 'Doctor', b: 'Nurse' },
  { category: 'Jobs', a: 'Chef', b: 'Baker' },
  { category: 'Jobs', a: 'Engineer', b: 'Architect' },
  { category: 'Jobs', a: 'Pilot', b: 'Driver' },
  { category: 'Jobs', a: 'Farmer', b: 'Gardener' },
  { category: 'Jobs', a: 'Police Officer', b: 'Firefighter' },
  { category: 'Jobs', a: 'Lawyer', b: 'Judge' },
  { category: 'Transport', a: 'Car', b: 'Motorcycle' },
  { category: 'Transport', a: 'Bus', b: 'Tram' },
  { category: 'Transport', a: 'Train', b: 'Subway' },
  { category: 'Transport', a: 'Bicycle', b: 'Scooter' },
  { category: 'Transport', a: 'Airplane', b: 'Helicopter' },
  { category: 'Transport', a: 'Boat', b: 'Ferry' },
  { category: 'Transport', a: 'Taxi', b: 'Rideshare' },
  { category: 'Transport', a: 'Rocket', b: 'Satellite' },
  { category: 'Home', a: 'Table', b: 'Chair' },
  { category: 'Home', a: 'Desk', b: 'Computer' },
  { category: 'Home', a: 'Fridge', b: 'Freezer' },
  { category: 'Home', a: 'Oven', b: 'Microwave' },
  { category: 'Home', a: 'Lamp', b: 'Candle' },
  { category: 'Home', a: 'Blanket', b: 'Pillow' },
  { category: 'Home', a: 'Broom', b: 'Vacuum' },
  { category: 'Home', a: 'Shower', b: 'Bathtub' },
  { category: 'Nature', a: 'River', b: 'Lake' },
  { category: 'Nature', a: 'Forest', b: 'Jungle' },
  { category: 'Nature', a: 'Rain', b: 'Snow' },
  { category: 'Nature', a: 'Sun', b: 'Moon' },
  { category: 'Nature', a: 'Volcano', b: 'Geyser' },
  { category: 'Nature', a: 'Island', b: 'Peninsula' },
  { category: 'Nature', a: 'Thunder', b: 'Lightning' },
  { category: 'Nature', a: 'Wind', b: 'Breeze' },
  { category: 'Entertainment', a: 'Movie', b: 'Series' },
  { category: 'Entertainment', a: 'Guitar', b: 'Piano' },
  { category: 'Entertainment', a: 'Painting', b: 'Sculpture' },
  { category: 'Entertainment', a: 'Novel', b: 'Comics' },
  { category: 'Entertainment', a: 'Dance', b: 'Ballet' },
  { category: 'Entertainment', a: 'Podcast', b: 'Radio' },
  { category: 'Entertainment', a: 'Concert', b: 'Festival' },
  { category: 'Entertainment', a: 'Chess', b: 'Poker' },
  { category: 'Clothing', a: 'Shirt', b: 'Jacket' },
  { category: 'Clothing', a: 'Shoes', b: 'Boots' },
  { category: 'Clothing', a: 'Hat', b: 'Cap' },
  { category: 'Clothing', a: 'Jeans', b: 'Shorts' },
  { category: 'Clothing', a: 'Gloves', b: 'Scarf' },
  { category: 'Clothing', a: 'Tie', b: 'Bow Tie' },
  { category: 'Clothing', a: 'Socks', b: 'Stockings' },
  { category: 'Clothing', a: 'Dress', b: 'Skirt' },
  { category: 'School', a: 'Pencil', b: 'Pen' },
  { category: 'School', a: 'Notebook', b: 'Textbook' },
  { category: 'School', a: 'Classroom', b: 'Laboratory' },
  { category: 'School', a: 'Exam', b: 'Quiz' },
  { category: 'School', a: 'Homework', b: 'Project' },
  { category: 'School', a: 'Blackboard', b: 'Whiteboard' },
  { category: 'School', a: 'Backpack', b: 'Locker' },
  { category: 'School', a: 'Eraser', b: 'Sharpener' },
  { category: 'Health', a: 'Dentist', b: 'Orthodontist' },
  { category: 'Health', a: 'Vitamins', b: 'Medicine' },
  { category: 'Health', a: 'Cardio', b: 'Strength Training' },
  { category: 'Health', a: 'Salad', b: 'Smoothie' },
  { category: 'Health', a: 'Sleep', b: 'Nap' },
  { category: 'Health', a: 'Yoga', b: 'Pilates' },
  { category: 'Health', a: 'Pharmacy', b: 'Clinic' },
  { category: 'Health', a: 'Thermometer', b: 'Stethoscope' },
  { category: 'Travel', a: 'Passport', b: 'Visa' },
  { category: 'Travel', a: 'Map', b: 'Compass' },
  { category: 'Travel', a: 'Hotel', b: 'Hostel' },
  { category: 'Travel', a: 'Luggage', b: 'Backpack' },
  { category: 'Travel', a: 'Souvenir', b: 'Postcard' },
  { category: 'Travel', a: 'Ticket', b: 'Boarding Pass' },
  { category: 'Travel', a: 'Guidebook', b: 'Itinerary' },
  { category: 'Travel', a: 'Border', b: 'Customs' }
];

export const WORD_DECK_CATEGORIES = [...new Set(DEFAULT_WORD_DECK.map((entry) => entry.category))];

const SPANISH_CATEGORY_TRANSLATIONS: Record<string, string> = {
  Food: 'Comida',
  Places: 'Lugares',
  Sports: 'Deportes',
  Animals: 'Animales',
  Tech: 'Tecnología',
  Jobs: 'Trabajos',
  Transport: 'Transporte',
  Home: 'Hogar',
  Nature: 'Naturaleza',
  Entertainment: 'Entretenimiento',
  Clothing: 'Ropa',
  School: 'Escuela',
  Health: 'Salud',
  Travel: 'Viajes'
};

const SPANISH_PHRASE_TRANSLATIONS: Record<string, string> = {
  'hot dog': 'perro caliente',
  'bow tie': 'corbata',
  'search engine': 'buscador',
  'train station': 'estacion de tren',
  'boarding pass': 'tarjeta de abordaje',
  'strength training': 'entrenamiento de fuerza',
  'whiteboard': 'pizarra',
  'boarding': 'embarque'
};

const SPANISH_TOKEN_TRANSLATIONS: Record<string, string> = {
  airplane: 'avion',
  airport: 'aeropuerto',
  apple: 'manzana',
  architect: 'arquitecto',
  armchair: 'sillon',
  recliner: 'reclinable',
  backpack: 'mochila',
  badminton: 'badminton',
  baker: 'panadero',
  ballet: 'ballet',
  banana: 'platano',
  baseball: 'beisbol',
  basketball: 'baloncesto',
  bathtub: 'bano',
  beach: 'playa',
  bear: 'oso',
  bed: 'cama',
  bicycle: 'bicicleta',
  bycicle: 'bicicleta',
  blackberry: 'mora',
  backboard: 'pizarra',
  bow: 'lazo',
  boxing: 'boxeo',
  breeze: 'brisa',
  broom: 'escoba',
  browser: 'navegador',
  burger: 'hamburguesa',
  bus: 'autobus',
  camera: 'camara',
  candle: 'vela',
  cap: 'gorro',
  car: 'coche',
  cardio: 'cardio',
  cat: 'gato',
  chef: 'cocinero',
  chess: 'ajedrez',
  city: 'ciudad',
  classroom: 'aula',
  clinic: 'clinica',
  coffee: 'cafe',
  comics: 'historieta',
  computer: 'computadora',
  compass: 'brujula',
  desk: 'escritorio',
  chair: 'silla',
  table: 'mesa',
  concert: 'concierto',
  couch: 'sofá',
  cricket: 'criquet',
  customs: 'aduanas',
  cycling: 'ciclismo',
  dance: 'danza',
  dentist: 'dentista',
  desert: 'desierto',
  doctor: 'doctor',
  dog: 'perro',
  dolphin: 'delfin',
  donkey: 'burro',
  dress: 'vestido',
  driver: 'conductor',
  drone: 'drone',
  eagle: 'aguila',
  empanada: 'empanada',
  engineer: 'ingeniero',
  eraser: 'borrador',
  exam: 'examen',
  farmer: 'granjero',
  ferry: 'transbordador',
  festival: 'festival',
  firefighter: 'bombero',
  forest: 'bosque',
  fox: 'zorro',
  freezer: 'congelador',
  fridge: 'nevera',
  gardener: 'jardinero',
  geyser: 'géiser',
  gloves: 'guantes',
  golf: 'golf',
  guidebook: 'guía',
  guitar: 'guitarra',
  handball: 'balonmano',
  hare: 'liebre',
  hat: 'sombrero',
  hawk: 'halcon',
  headphones: 'auriculares',
  helicopter: 'helicoptero',
  homework: 'tarea',
  horse: 'caballo',
  hospital: 'hospital',
  hostel: 'hostal',
  hot: 'caliente',
  hotel: 'hotel',
  island: 'isla',
  itinerary: 'itinerario',
  jacket: 'chaqueta',
  jeans: 'vaqueros',
  judge: 'juez',
  jungle: 'selva',
  keyboard: 'teclado',
  laboratory: 'laboratorio',
  lake: 'lago',
  lamp: 'lampara',
  laptop: 'portatil',
  lawyer: 'abogado',
  library: 'biblioteca',
  lightning: 'rayo',
  lion: 'leon',
  locker: 'taquilla',
  luggage: 'equipaje',
  map: 'mapa',
  medicine: 'medicina',
  microwave: 'microondas',
  moon: 'luna',
  motorcycle: 'motocicleta',
  mountain: 'montana',
  mouse: 'raton',
  movie: 'pelicula',
  museum: 'museo',
  nap: 'siesta',
  notebook: 'cuaderno',
  novel: 'novela',
  nurse: 'enfermera',
  orthodontist: 'ortodoncista',
  oven: 'horno',
  painting: 'pintura',
  pancakes: 'panqueques',
  panda: 'panda',
  park: 'parque',
  passport: 'pasaporte',
  pasta: 'pasta',
  pen: 'pluma',
  pencil: 'lapiz',
  peninsula: 'peninsula',
  pharmacy: 'farmacia',
  phone: 'telefono',
  piano: 'piano',
  pilates: 'pilates',
  pillow: 'almohada',
  pilot: 'piloto',
  pizza: 'pizza',
  plaza: 'plaza',
  podcast: 'podcast',
  poker: 'poker',
  police: 'policia',
  postcard: 'postal',
  printer: 'impresora',
  professor: 'profesor',
  project: 'proyecto',
  quiz: 'cuestionario',
  rabbit: 'conejo',
  radio: 'radio',
  rain: 'lluvia',
  risotto: 'risotto',
  river: 'rio',
  robot: 'robot',
  rocket: 'cohete',
  running: 'carrera',
  salad: 'ensalada',
  satellite: 'satellite',
  scanner: 'scanner',
  scarf: 'bufanda',
  scooter: 'monopatin',
  sculpture: 'escultura',
  series: 'serie',
  shark: 'tiburon',
  sharpener: 'sacapuntas',
  shirt: 'camisa',
  shoes: 'zapatos',
  shorts: 'shorts',
  shower: 'ducha',
  skirt: 'falda',
  sleep: 'sueño',
  smoothie: 'batido',
  snow: 'nieve',
  soccer: 'futbol',
  socks: 'calcetines',
  sofa: 'sofa',
  soup: 'sopa',
  souvenir: 'souvenir',
  speakers: 'altavoces',
  stadium: 'estadio',
  station: 'estacion',
  stethoscope: 'estetoscopio',
  stew: 'guiso',
  stockings: 'medias',
  subway: 'subte',
  sun: 'sol',
  surfing: 'surf',
  sushi: 'sushi',
  swimming: 'natacion',
  tablet: 'tableta',
  tacos: 'tacos',
  taxi: 'taxi',
  tea: 'te',
  teacher: 'maestro',
  tennis: 'tenis',
  textbook: 'libro de texto',
  theater: 'teatro',
  thermometer: 'termometro',
  thunder: 'trueno',
  ticket: 'entrada',
  tie: 'corbata',
  tiger: 'tigre',
  town: 'pueblo',
  train: 'tren',
  tram: 'tranvia',
  vacuum: 'aspiradora',
  valley: 'valle',
  visa: 'visa',
  vitamins: 'vitaminas',
  volcano: 'volcan',
  volleyball: 'voley',
  waffles: 'waffles',
  wind: 'viento',
  wolf: 'lobo',
  wrestling: 'lucha',
  yoga: 'yoga'
};

const normalizeLocaleWord = (word: string) => word.trim().toLowerCase();

const translateToken = (word: string, locale: WordLocale): string => {
  if (locale === 'en') {
    return word;
  }

  const lower = normalizeLocaleWord(word);
  return SPANISH_TOKEN_TRANSLATIONS[lower] ?? word;
};

const translateWord = (word: string, locale: WordLocale): string => {
  if (locale === 'en') {
    return word;
  }

  const lower = normalizeLocaleWord(word);
  const phrase = SPANISH_PHRASE_TRANSLATIONS[lower];
  if (phrase) {
    return phrase;
  }

  return word
    .split(/([\s-])/)
    .map((part) => (part.trim() ? translateToken(part, locale) : part))
    .join('')
    .replace('\b', '');
};

export const localizeWordPair = (pair: WordPair, locale: WordLocale): WordPair => {
  if (locale === 'en') {
    return pair;
  }

  return {
    ...pair,
    category: pair.category ? localizeCategory(pair.category, locale) : pair.category,
    a: translateWord(pair.a, locale),
    b: translateWord(pair.b, locale)
  };
};

export const localizeCategory = (category: string, locale: WordLocale): string => {
  if (locale === 'en') {
    return category;
  }

  const normalized = category.trim();
  return SPANISH_CATEGORY_TRANSLATIONS[normalized] ?? normalized;
};
